# Generated by Django 5.2.6 on 2025-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothesshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="primary_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="secondary_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
