# Generated by Django 5.2.6 on 2025-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesshop', '0004_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.AddField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
