# Generated by Django 5.2.6 on 2025-10-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesshop', '0005_remove_sale_address_remove_sale_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='size',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='clothesshop.listing')),
            ],
            options={
                'unique_together': {('listing', 'size')},
            },
        ),
    ]
