# Generated by Django 5.2.6 on 2025-10-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesshop', '0006_remove_listing_size_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='secondary_image',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothesshop.listing')),
            ],
        ),
    ]
