# Generated by Django 5.2.6 on 2025-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothesshop", "0007_remove_listing_primary_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingimage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="listingimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Set the display order. 0 will be the primary image.",
            ),
        ),
    ]
